version: '3.7'

services:
  db:
    image: postgres:9.5
    network_mode: host
    ports:
      - '5432:5432'
    volumes:
      - './tmp/volumes/db:/var/lib/postgresql/data'

  redis:
    image: redis:3.2.11
    network_mode: host
    ports:
      - '6379:6379'
    volumes:
      - './docker/redis/redis.conf:/etc/redis.conf'
      - './tmp/volumes/redis:/data'
    command: redis-server /etc/redis.conf

  es:
    image: elasticsearch:5.6.8
    network_mode: host
    ports:
      - '9200:9200'
    environment:
      # Set memory
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      # Disable security
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
      # Run in development mode to ignore bootstrap checks
      transport.host: "localhost"
    volumes:
      - './tmp/volumes/es:/usr/share/elasticsearch/data'
