version: '3.7'

services:
  proxy:
    image: nginx
    network_mode: host
    ports:
      - '80:80'
    # uncomment to vizualise
    # depends_on:
    #   - api
    #   - buyer
    #   - exopps
    #   - sso
    #   - ssoproxy
    #   - supplier
    #   - profile
    #   - domestic
    #   - soo
    #   - cms
    #   - formsapi
    #   - invest
    #   - international
    volumes:
      - './docker/proxy/default.conf:/etc/nginx/conf.d/default.conf'

  db:
    image: postgres:9.5
    networks:
      uktrade-network:
    ports:
      - '5432:5432'
    volumes:
      - './tmp/volumes/db:/var/lib/postgresql/data'

  redis:
    image: redis:3.2.11
    networks:
      uktrade-network:
    ports:
      - '6379:6379'
    volumes:
      - './docker/redis/redis.conf:/etc/redis.conf'
      - './tmp/volumes/redis:/data'
    command: redis-server /etc/redis.conf

  es:
    image: elasticsearch:5.6.8
    networks:
      uktrade-network:
    ports:
      - '9200:9200'
    environment:
      # Set memory
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      # Disable security
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
      # Run in development mode to ignore bootstrap checks
      transport.host: "localhost"
    volumes:
      - './tmp/volumes/es:/usr/share/elasticsearch/data'

  api:
    image: local-workspace/directory-api
    build:
      context: ../directory-api/
      dockerfile: new_Dockerfile
    networks:
      uktrade-network:
        aliases:
          - api.trade.great
    ports:
      - '8000:8000'
    env_file:
      - ../directory-api/.new_env
    volumes:
      - '../directory-api:/usr/src/app'
    depends_on:
      - db
      - redis
      - es

  buyer:
    image: local-workspace/directory-ui-buyer
    build:
      context: ../directory-ui-buyer/
      dockerfile: new_Dockerfile
    networks:
      uktrade-network:
        aliases:
          - buyer.trade.great
    ports:
      - '8001:8001'
    env_file:
      - ../directory-ui-buyer/.new_env
    volumes:
      - '../directory-ui-buyer:/usr/src/app'
    depends_on:
      - redis
      - ssoproxy

  exopps:
    image: local-workspace/export-opportunities
    build:
      context: ../export-opportunities/
      dockerfile: new_Dockerfile
    networks:
      uktrade-network:
        aliases:
          - opportunities.export.great
    ports:
      - '8002:8002'
    depends_on:
      - db
    env_file:
      - ../export-opportunities/.new_env
    volumes:
      - '../export-opportunities:/usr/src/app'
    depends_on:
      - redis
      - es
      - ssoproxy

  sso:
    image: local-workspace/directory-sso
    build:
      context: ../directory-sso/
      dockerfile: new_Dockerfile
    networks:
      uktrade-network:
        aliases:
          - sso.trade.great
    ports:
      - '8003:8003'
    env_file:
      - ../directory-sso/.new_env
    volumes:
      - '../directory-sso:/usr/src/app'
    depends_on:
      - db
      - redis

  ssoproxy:
    image: local-workspace/directory-sso-proxy
    build:
      context: ../directory-sso-proxy/
      dockerfile: new_Dockerfile
    networks:
      uktrade-network:
        aliases:
          - sso-proxy.trade.great
    ports:
      - '8004:8004'
    env_file:
      - ../directory-sso-proxy/.new_env
    volumes:
      - '../directory-sso-proxy:/usr/src/app'
    depends_on:
      - sso

  supplier:
    image: local-workspace/directory-ui-supplier
    build:
      context: ../directory-ui-supplier/
      dockerfile: new_Dockerfile
    networks:
      uktrade-network:
        aliases:
          - supplier.trade.great
    ports:
      - '8005:8005'
    env_file:
      - ../directory-ui-supplier/.new_env
    volumes:
      - '../directory-ui-supplier:/usr/src/app'
    depends_on:
      - cms
      - ssoproxy

  profile:
    image: local-workspace/directory-sso-profile
    build:
      context: ../directory-sso-profile/
      dockerfile: new_Dockerfile
    networks:
      uktrade-network:
        aliases:
          - profile.trade.great
    ports:
      - '8006:8006'
    env_file:
      - ../directory-sso-profile/.new_env
    volumes:
      - '../directory-sso-profile:/usr/src/app'
    depends_on:
      - cms
      - ssoproxy

  domestic:
    image: local-workspace/great-domestic-ui
    build:
      context: ../great-domestic-ui/
      dockerfile: new_Dockerfile
    networks:
      uktrade-network:
        aliases:
          - exred.trade.great
    ports:
      - '8007:8007'
    env_file:
      - ../great-domestic-ui/.new_env
    volumes:
      - '../great-domestic-ui:/usr/src/app'
    depends_on:
      - db
      - redis
      - api
      - cms
      - formsapi
      - ssoproxy

  soo:
    image: local-workspace/navigator
    build:
      context: ../navigator/
      dockerfile: new_Dockerfile
    networks:
      uktrade-network:
        aliases:
          - soo.trade.great
    ports:
      - '8008:8008'
    env_file:
      - ../navigator/.new_env
    volumes:
      - '../navigator:/usr/src/app'
    depends_on:
      - db
      - ssoproxy

  cms:
    image: local-workspace/directory-cms
    build:
      context: ../directory-cms/
      dockerfile: new_Dockerfile
    networks:
      uktrade-network:
        aliases:
          - cms.trade.great
    ports:
      - '8010:8010'
    env_file:
      - ../directory-cms/.new_env
    volumes:
      - '../directory-cms:/usr/src/app'
    depends_on:
      - db
      - redis

  formsapi:
    image: local-workspace/directory-forms-api
    build:
      context: ../directory-forms-api/
      dockerfile: new_Dockerfile
    networks:
      uktrade-network:
        aliases:
          - forms.trade.great
    ports:
      - '8011:8011'
    env_file:
      - ../directory-forms-api/.new_env
    volumes:
      - '../directory-forms-api:/usr/src/app'
    depends_on:
      - db
      - redis

  invest:
    image: local-workspace/invest-ui
    build:
      context: ../invest-ui/
      dockerfile: new_Dockerfile
    networks:
      uktrade-network:
        aliases:
          - invest.trade.great
    ports:
      - '8012:8012'
    env_file:
      - ../invest-ui/.new_env
    volumes:
      - '../invest-ui:/usr/src/app'
    depends_on:
      - db
      - redis
      - cms
      - ssoproxy

  international:
    image: local-workspace/great-international-ui
    build:
      context: ../great-international-ui/
      dockerfile: new_Dockerfile
    networks:
      uktrade-network:
        aliases:
          - international.trade.great
    ports:
      - '8013:8013'
    env_file:
      - ../great-international-ui/.new_env
    volumes:
      - '../great-international-ui:/usr/src/app'
    depends_on:
      - db
      - redis
      - cms
      - formsapi
      - ssoproxy

networks:
  uktrade-network:
