default: &default
  adapter: postgresql
  encoding: unicode
  host: 0.0.0.0
  username: debug
  password: debug
  pool: <%= [Figaro.env.db_pool.to_i, Figaro.env.threads.to_i, 64].max %>

development:
  <<: *default
  database: export_opportunities_dev_zeus

test:
  <<: *default
  database: export_opportunities_test

production:
  <<: *default
  database: ukti_opportunities_prod
